### ISSUE TITLE
Incompatible with TypeScript 4.3

### ISSUE THREAD

**Issue by shaharov** [andywer/observable-fns#17]
Compiling using the newest GA Typescript 4.3  throws the following error:
```
node_modules/observable-fns/dist/observable.d.ts:57:10 - error TS2368: Type parameter name cannot be 'never'.

57     pipe<never, Out extends ObservableLike<T>>(...mappers: Array<(input: Out) => Out>): Out;
            ~~~~~
```

**Comment by andywer** [comment]
Thanks for reporting, @shaharov!

Does it only fail to compile `observable-fns` or does it also fail to compile any project using the library?
It's definitely a rare encounter as TypeScript always tries to stay backwards-compatible. Any chance it already doesn't work with TypeScript 4.0?

**Comment by shaharov** [comment]
Compiling Threads.js raises an error as well.
No problems with version 4.2.4

**Comment by andywer** [comment]
Fixed version published as v0.6.0 😉

Still need to update threads.js (could take a little bit longer).
